# Generated by Django 5.1.3 on 2025-01-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordevice',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
