# Generated by Django 5.1.6 on 2025-02-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_chatroom_alter_audioevent_timestamp_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordevice',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
